server:
  port: 8222
spring:
  application:
    name: service-gataway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/*/acl/**
